# Generated by Django 4.1.4 on 2022-12-15 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=500)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('gender', models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=50)),
            ],
        ),
    ]
